const songsData = [
        /*
    {
        "title": "song",
        "artist": "singer",
        "lyrics": [
        
        ]
    },
    */
    {
        "title": "Breakdown",
        "artist": "Tom Petty and the Heartbreakers",
        "lyrics": [
            "It's alright if you love me",
            "It's alright if you don't",
            "I'm not afraid of you running away",
            "Honey, I get the feeling you won't",
            "There is no sense in pretending",
            "Your eyes give you away",
            "Something inside you is feeling like I do",
            "We've said all there is to say",
            "Baby",
            "Breakdown, go ahead, give it to me",
            "Breakdown, honey, take me through the night (take me, baby, breakdown)",
            "Breakdown, now I'm standing here, can you see? (Ooh-ooh)",
            "Breakdown, it's alright",
            "It's alright (ooh)",
            "It's alright"
        ]
    },
    {
        "title": "The Bad Touch",
        "artist": "Bloodhound Gang",
        "lyrics": [
            "Sweat baby, sweat baby, sex is a Texas drought",
            "Me and you do the kind of stuff that only Prince would sing about",
            "So put your hands down my pants and I'll bet you'll feel nuts",
            "Yes, I'm Siskel, yes, I'm Ebert and you're getting two thumbs up",
            "You've had enough of two-hand touch, you want it rough, you're out of bounds",
            "I want you smothered, want you covered, like my Waffle House hash browns",
            "Come quicker than FedEx, never reach an apex, just like Coca-Cola stock, you are inclined",
            "To make me rise an hour early, just like Daylight Savings Time",
            "Do it now",
            "You and me, baby, ain't nothing but mammals",
            "So let's do it like they do on the Discovery Channel",
            "Do it again now",
            "Getting horny now"
        ]
    },
    {
        "title": "Bridge Over Troubled Water",
        "artist": "Simon and Garfunkel",
        "lyrics": [
            "When you're weary",
            "Feeling small",
            "When tears are in your eyes",
            "I'll dry them all",
            "I'm on your side",
            "Oh, when times get rough",
            "And friends just can't be found",
            "Like a bridge over troubled water",
            "I will lay me down",
            "Like a bridge over troubled water",
            "I will lay me down",
            "When you're down and out",
            "When you're on the street",
            "When evening falls so hard",
            "I will comfort you",
            "I'll take your part",
            "Oh, when darkness comes"
        ]
    },
    {
        "title": "Take it Easy",
        "artist": "Eagles",
        "lyrics": [
            "Well, I'm runnin' down the road tryna loosen my load",
            "I got seven women on my mind",
            "Four that wanna own me, two that wanna stone me",
            "One says she's a friend of mine",
            "Take it easy, take it easy",
            "Don't let the sound of your own wheels drive you crazy",
            "Lighten up while you still can",
            "Don't even try to understand",
            "Just find a place to make your stand and take it easy",
            "Well, I'm a-standin' on a corner in Winslow, Arizona",
            "And such a fine sight to see",
            "It's a girl, my Lord, in a flatbed Ford",
            "Slowin' down to take a look at me",
            "Come on, baby, don't say maybe",
            "I gotta know if your sweet love is gonna save me",
            "We may lose and we may win",
            "Though we will never be here again",
            "So open up, I'm climbin' in",
            "So take it easy"
        ]
    },
    {
        "title": "Ventura Highway",
        "artist": "America",
        "lyrics": [
            "Chewin' on a piece of grass, walkin' down the road",
            "Tell me, how long you gonna stay here, Joe?",
            "Some people say this town don't look good in snow",
            "You don't care, I know",
            "Ventura Highway in the sunshine",
            "Where the days are longer",
            "The nights are stronger than moonshine",
            "You're gonna go, I know",
            "'Cause the free wind is blowin' through your hair",
            "And the days surround your daylight there",
            "Seasons crying no despair",
            "Alligator lizards in the air, in the air",
            "Wishin' on a falling star, waitin' for the early train",
            "Sorry boy, but I've been hit by a purple rain",
            "Aw, c'mon Joe, you can always change your name",
            "Thanks a lot son, just the same",
            "Ventura Highway in the sunshine",
            "Where the days are longer",
            "The nights are stronger than moonshine",
            "You're gonna go, I know"
        ]
    },
    {
        "title": "Driver 8",
        "artist": "R.E.M.",
        "lyrics": [
            "The walls are built up stone by stone",
            "The fields divided one by one",
            "And the train conductor says",
            "Take a break, Driver 8",
            "Driver 8, take a break",
            "We've been on this shift too long",
            "And the train conductor says",
            "Take a break, driver 8",
            "Driver 8, take a break",
            "We can reach our destination",
            "But we're still a ways away, but it's still a ways away",
            "I saw a treehouse on the outskirts of the farm",
            "The power lines have floaters so the airplanes won't get snagged",
            "The bells are ringing through the town again",
            "The children look up, all they hear is sky-blue bells ringing",
            "And the train conductor says",
            "Take a break, Driver 8",
            "Driver 8, take a break",
            "We can reach our destination",
            "But we're still a ways away, but it's still a ways away",
            "But we're still a ways away, but it's still a ways away",
            "A way to shield the hated heat",
            "A way to put myself to sleep",
            "A way to shield the hated heat",
            "A way to put myself, my children to sleep"
        ]
    },
    {
        "title": "Black Magic Woman",
        "artist": "Eric Clapton",
        "lyrics": [
            "Got a black magic woman",
            "Got a black magic woman",
            "Got a black magic woman",
            "Got me so blind, I can't see",
            "That she's a black magic woman",
            "Tryna make a devil outta me",
            "Don't turn your back on me, baby",
            "Don't turn your back on me, baby",
            "Don't turn your back on me, baby",
            "Fooling 'round with your tricks",
            "'Cause you're a black magic woman",
            "Might wake up my magic sticks",
            "You put a spell on me, baby",
            "You put a spell on me, baby",
            "You put a spell on me, baby",
            "Got me so blind, I can't see",
            "That you're a black magic woman",
            "Tryna make a devil outta me"
        ]
    },
    {
        "title": "Have You Ever Seen the Rain",
        "artist": "Creedence Clearwater Revival",
        "lyrics": [
            "Someone told me long ago",
            "There's a calm before the storm",
            "I know, it's been comin' for some time",
            "When it's over, so they say",
            "It'll rain a sunny day",
            "I know, shinin' down like water",
            "I wanna know, have you ever seen the rain?",
            "I wanna know, have you ever seen the rain?",
            "Comin' down on a sunny day",
            "Yesterday, and days before",
            "Sun is cold and rain is hard",
            "I know, been that way for all my time",
            "'Til forever, on it goes",
            "Through the circle, fast and slow",
            "I know, it can't stop, I wonder",
            "I wanna know, have you ever seen the rain?",
            "I wanna know, have you ever seen the rain?",
            "Comin' down on a sunny day",
            "I wanna know, have you ever seen the rain?",
            "Comin' down on a sunny day"
        ]
    },
    {
        "title": "Fast Car",
        "artist": "Tracy Chapman",
        "lyrics": [
            "You got a fast car",
            "I want a ticket to anywhere",
            "Maybe we can make a deal",
            "Maybe together we can get somewhere",
            "Any place is better",
            "Starting from zero, got nothing to lose",
            "Maybe we'll make something",
            "Me, myself, I got nothing to prove",
            "You got a fast car",
            "I got a plan to get us out of here",
            "I been working at the convenience store",
            "Managed to save just a little bit of money",
            "Won't have to drive too far",
            "Just 'cross the border and into the city",
            "You and I can both get jobs",
            "And finally see what it means to be living",
            "See, my old man's got a problem",
            "He live with the bottle, that's the way it is",
            "He say his body's too old for working",
            "His body's too young to look like his",
            "My mama went off and left him",
            "She wanted more from life than he could give",
            "I said somebody's got to take care of him",
            "So I quit school and that's what I did"]
    },
    {
        "title": "When You Awake",
        "artist": "The Band",
        "lyrics": [
            "Ollie told me that I'm a fool",
            "So I walked on down the road a mile",
            "Then went to the house that brings a smile",
            "Sat upon my grandpa's knee, and what do you think he said to me?",
            "When you awake you will remember everything",
            "You will be hanging' on a string",
            "When you believe, you will relieve the only soul",
            "That you were born with to grow old and never know",
            "Ollie, you showed me the fork in the road",
            "You said that, You can take to the left or go straight to the right",
            "Save your days and use your nights",
            "Be careful where you step, and watch what do you eat",
            "Sleep with the light on and you got it beat",
            "When you awake you will remember everything",
            "You will be hanging' on a string, yeah",
            "When you believe, you will relieve the only soul",
            "That you were born with to grow old and never know"
        ]
    },
    {
        "title": "Sweet Caroline",
        "artist": "Neil Diamond",
        "lyrics": [
            "Where it began",
            "I can't begin to know when",
            "But then I know it's growin' strong",
            "Was in the spring",
            "And spring became the summer",
            "Who'd have believe you'd come along?",
            "Hands",
            "Touchin' hands",
            "Reachin' out",
            "Touching me, touchin' you",
            "Sweet Caroline",
            "Good times never seemed so good",
            "I've been inclined",
            "To believe they never would",
            "But now I look at the night",
            "And it don't seem so lonely",
            "We fill it up with only two",
            "And when I hurt",
            "Hurtin' runs off my shoulders",
            "How can I hurt when holdin' you?",
            "Warm",
            "Touchin' warm",
            "Reachin' out",
            "Touchin' me, touchin' you"
        ]
    },
    {
        "title": "Wagon Wheel",
        "artist": "Darius Rucker",
        "lyrics": [
            "Headin' down south to the land of the pines",
            "I'm thumbin' my way into North Caroline",
            "Starin' up the road and pray to God I see headlights",
            "I made it down the coast in seventeen hours",
            "Pickin' me a bouquet of dogwood flowers",
            "And I'm a-hopin' for Raleigh, I can see my baby tonight",
            "So, rock me mama like a wagon wheel",
            "Rock me mama any way you feel",
            "Hey... mama rock me",
            "Rock me mama like the wind and the rain",
            "Rock me mama like a southbound train",
            "Hey... mama rock me",
            "Runnin' from the cold up in New England",
            "I was born to be a fiddler in an old time string band",
            "My baby plays a guitar, I pick a banjo now",
            "Oh, north country winters keep a-gettin' me down",
            "Lost my money playin' poker, so I had to leave town",
            "But I ain't a-turnin' back to livin' that old life no more"
        ]
    },
    {
        "title": "Escape (The Pina Colada Song)",
        "artist": "Rupert Holmes",
        "lyrics": [
            "I was tired of my lady",
            "We'd been together too long",
            "Like a worn out recording",
            "Of a favorite song",
            "So while she lay there sleepin'",
            "I read the paper in bed",
            "And in the personal columns",
            "There was this letter I read",
            "If you like piña coladas",
            "And gettin' caught in the rain",
            "If you're not into yoga",
            "If you have half a brain",
            "If you like makin' love at midnight",
            "In the dunes on the cape",
            "Then I'm the love that you've looked for",
            "Write to me and escape",
            "I didn't think about my lady",
            "I know that sounds kinda mean",
            "But me and my old lady",
            "Had fallen into the same old dull routine"
        ]
    },
    {
        "title": "Space Oddity",
        "artist": "David Bowie",
        "lyrics": [
            "Ground Control to Major Tom",
            "Ground Control to Major Tom",
            "Take your protein pills and put your helmet on",
            "(Ten) Ground Control (Nine) to Major Tom (Eight, seven)",
            "(Six) Commencing (Five) countdown, engines on",
            "(Four, three, two)",
            "Check ignition (One) and may God's love (Lift off) be with you",
            "[Instrumental Bridge]",
            "[Verse 2]",
            "This is Ground Control to Major Tom",
            "You've really made the grade",
            "And the papers want to know whose shirts you wear",
            "Now it's time to leave the capsule if you dare",
            "This is Major Tom to Ground Control",
            "I'm stepping through the door",
            "And I'm floating in a most peculiar way",
            "And the stars look very different today",
            "[Chorus]",
            "For here am I sitting in my tin can",
            "Far above the world",
            "Planet Earth is blue",
            "And there's nothing I can do"
        ]
    },
    {
        "title": "Piano Man",
        "artist": "Billy Joel",
        "lyrics": [
            "It's nine o'clock on a Saturday",
            "The regular crowd shuffles in",
            "There's an old man sittin' next to me",
            "Makin' love to his tonic and gin",
            "He says, Son can you play me a memory?",
            "I'm not really sure how it goes",
            "But it's sad and it's sweet and I knew it complete",
            "When I wore a younger man's clothes",
            "La, la-la, di-di-da",
            "La-la di-di-da da-dum",
            "Sing us a song, you're the piano man",
            "Sing us a song tonight",
            "Well, we're all in the mood for a melody",
            "And you've got us feelin' alright",
            "Now John at the bar is a friend of mine",
            "He gets me my drinks for free",
            "And he's quick with a joke, or to light up your smoke",
            "But there's some place that he'd rather be"
        ]
    },
    {
        "title": "Time for Me to Fly",
        "artist": "REO Speedwagon",
        "lyrics": [
            "I've been around for you",
            "Been up and down for you",
            "But I just can't get any relief",
            "I've swallowed my pride for you",
            "Lived and lied for you",
            "But you still make me feel like a thief",
            "You got me stealin' your love away",
            "'Cause you never give it",
            "Peelin' the years away",
            "And we can't relive it",
            "Oh, I make you laugh",
            "And you make me cry",
            "I believe it's time for me to fly",
            "You said we'd work it out",
            "You said that ya had no doubt",
            "That deep down we were really in love",
            "Oh, but I'm tired of holdin' on",
            "To a feelin' I know is gone",
            "I do believe that I've had enough"
        ]
    },
    {
        "title": "Peaceful Easy Feeling",
        "artist": "Eagles",
        "lyrics": [
            "I like the way your sparkling earrings lay",
            "Against your skin so brown",
            "And I wanna sleep with you in the desert tonight",
            "With a billion stars all around",
            "'Cause I gotta peaceful, easy feeling",
            "And I know you won't let me down",
            "'Cause I'm already standing",
            "On the ground",
            "And I found out a long time ago",
            "What a woman can do to your soul",
            "Oh, but she can't take you anyway",
            "You don't already know how to go",
            "And I gotta peaceful, easy feeling",
            "And I know you won't let me down",
            "'Cause I'm already standing (ooh, ooh, ooh)",
            "On the ground"
        ]
    },
    {
        "title": "The Long and Winding Road",
        "artist": "The Beatles",
        "lyrics": [
            "The long and winding road",
            "That leads to your door",
            "Will never disappear",
            "I've seen that road before",
            "It always leads me here",
            "Lead me to your door",
            "The wild and windy night",
            "That the rain washed away",
            "Has lefted full of tears",
            "Crying for the day",
            "Why leave me standing here",
            "Let me know the way",
            "Many times I've been alone",
            "And many times I've cried",
            "Anyway you'll never know",
            "The many ways I've tried"
        ]
    },
    {
        "title": "Can't Buy Me Love",
        "artist": "The Beatles",
        "lyrics": [
            "I'll buy you a diamond ring my friend",
            "If it makes you feel alright",
            "I'll get you anything my friend",
            "If it makes you feel alright",
            "'Cause I don't care too much for money",
            "For money can't buy me love",
            "I'll give you all I've got to give",
            "If you say you love me too",
            "I may not have a lot to give",
            "But what I've got, I'll give to you",
            "I don't care too much for money",
            "Money can't buy me love",
            "Can't buy me love",
            "Everybody tells me so",
            "Can't buy me love",
            "No, no, no, no"
        ]
    },
    {
        "title": "Let It Bleed",
        "artist": "The Rolling Stones",
        "lyrics": [
            "Well, we all need someone we can lean on ",
            "And if you want it, you can lean on me ",
            "Yeah, we all need someone we can lean on ",
            "And if you want it, you can lean on me ",
            "She said, 'My breasts, they will always be open ",
            "Baby, you can rest your weary head right on me ",
            "And there will always be a space in my parking lot ",
            "When you need a little coke and sympathy ",
            "Yeah, we all need someone we can dream on ",
            "And if you want it, baby, well you can dream on me ",
            "Yeah, we all need someone we can cream on ",
            "And if you want to, well you can cream on me ",
            "I was dreaming of a steel guitar engagement ",
            "When you drunk my health in scented jasmine tea ",
            "But you knifed me in my dirty filthy basement ",
            "With that jaded, faded, junky nurse ",
            "Oh what pleasant company ",
    
        ]
    },
    {
        "title": "American Pie",
        "artist": "Don McLean",
        "lyrics": [
            "A long, long time ago",
            "I can still remember how that music",
            "Used to make me smile",
            "And I knew if I had my chance",
            "That I could make those people dance",
            "And maybe they'd be happy for a while",
            "But February made me shiver",
            "With every paper I'd deliver",
            "Bad news on the doorstep",
            "I couldn't take one more step",
            "I can't remember if I cried",
            "When I read about his widowed bride",
            "But something touched me deep inside",
            "The day the music died",
            "A long, long time ago",
            "I can still remember how that music",
            "Used to make me smile",
            "And I knew if I had my chance",
            "That I could make those people dance",
            "And maybe they'd be happy for a while",
            "But February made me shiver",
            "With every paper I'd deliver"
        ]
    },
    {
        "title": "Words",
        "artist": "Bee Gees",
        "lyrics": [
            "Smile an everlasting smile",
            "A smile can bring you near to me",
            "Don't ever let me find you down",
            "'Cause that would bring a tear to me",
            "This world has lost its glory",
            "Let's start a brand new story now, my love",
            "Right now, there'll be no other time",
            "And I can show you how, my love",
            "Talk in everlasting words",
            "And dedicate them all to me",
            "And I will give you all my life",
            "I'm here if you should call to me",
            "You think that I don't even mean",
            "A single word I say",
            "It's only words and words are all I have",
            "To take your heart away",
        ]
    },
    {
        "title": "成都",
        "artist": "赵磊",
        "lyrics": [
            "让我掉下眼泪的",
            "不止昨夜的酒",
            "让我依依不舍的",
            "不止你的温柔",
            "余路还要走多久",
            "你攥着我的手",
            "让我感到为难的",
            "是挣扎的自由",
            "分别总是在九月",
            "回忆是思念的愁",
            "深秋嫩绿的垂柳",
            "亲吻着我额头",
            "在那座阴雨的小城里",
            "我从未忘记你",
            "成都 带不走的 只有你",
            "和我在成都的街头走一走",
            "直到所有的灯都熄灭了也不停留",
            "你会挽着我的衣袖",
            "我会把手揣进裤兜",
            "走到玉林路的尽头",
            "坐在小酒馆的门口",
            "分别总是在九月",
            "回忆是思念的愁",
            "深秋嫩绿的垂柳",
        ]
    },
    {
        "title": "Comfortably Numb",
        "artist": "Pink Floyd",
        "lyrics": [
            "[Verse 1: Roger Waters]",
            "Hello? (Hello, hello, hello)",
            "Is there anybody in there?",
            "Just nod if you can hear me",
            "Is there anyone home?",
            "Come on (Come on, come on), now",
            "I hear you're feeling down",
            "Well, I can ease your pain",
            "And get you on your feet again",
            "Relax (Relax, relax, relax)",
            "I'll need some information first",
            "Just the basic facts",
            "Can you show me where it hurts?",
            "There is no pain, you are receding",
            "A distant ship, smoke on the horizon",
            "You are only coming through in waves",
            "Your lips move, but I can't hear what you're saying",
            "When I was a child, I had a fever",
            "My hands felt just like two balloons",
            "Now I've got that feeling once again",
            "I can't explain, you would not understand",
            "This is not how I am",
            "I have become comfortably numb",
            "I have become comfortably numb",
            "Okay (Okay, okay, okay)",
            "Just a little pinprick",
            "There'll be no more",
            "But you may feel a little sick",
            "Can you stand up? (Stand up, stand up)",
            "I do believe it's working, good",
            "That'll keep you going through the show",
            "Come on, it's time to go",
            "There is no pain, you are receding",
            "A distant ship, smoke on the horizon",
            "You are only coming through in waves",
            "Your lips move, but I can't hear what you're saying",
            "When I was a child, I caught a fleeting glimpse",
            "Out of the corner of my eye",
            "I turned to look, but it was gone",
            "I cannot put my finger on it now",
            "The child is grown, the dream is gone"
        ]
    },
    {
        "title": "Sometimes When We Touch",
        "artist": "Dan Hill",
        "lyrics": [
            "You ask me if I love you",
            "And I choke on my reply",
            "I'd rather hurt you, honestly",
            "Than mislead you with a lie",
            "And who am I to judge you",
            "On what you say or do?",
            "I'm only just beginning",
            "To see the real you",
            "And sometimes when we touch",
            "The honesty's too much",
            "And I have to close my eyes and hide",
            "I wanna hold you 'til I die",
            "'Til we both break down and cry",
            "I wanna hold you",
            "'Til the fear in me subsides",
            "Romance and all its strategy",
            "Leaves me battling with my pride",
            "But through the insecurity",
            "Some tenderness survives",
            "I'm just another writer",
            "Still trapped within my truth",
            "A hesitant prize fighter",
            "Still trapped within my youth",
            "Sometimes when we touch",
            "The honesty's too much",
            "And I have to close my eyes and hide",
            "I wanna hold you 'til I die",
            "'Til we both break down and cry",
            "I wanna hold you",
            "'Til the fear in me subsides",
        ]
    },
    {
        "title": "Stayin' Alive",
        "artist": "Bee Gees",
        "lyrics": [
            "Well, you can tell by the way I use my walk",
            "I'm a woman's man, no time to talk",
            "The music loud and the women warm",
            "I've been kicked around since I was born",
            "Well, now it's alright, that's okay",
            "And you may look the other way",
            "We can try to understand",
            "The New York Times' effect on man",
            "Whether you're a brother or whether you're a mother",
            "You're stayin' alive, stayin' alive",
            "Feel the city breakin' and everybody shakin'",
            "And we're stayin' alive, stayin' alive",
            "Ah, ha, ha, ha, stayin' alive, stayin' alive",
            "Ah, ha, ha, ha, stayin' alive",
            "Help me, woman",
            "Well now, I get low and I get high",
            "And if I can't get either, I really try",
            "Got the wings of heaven on my shoes",
            "I'm a dancing man and I just can't lose",
            "You know it's alright, it's okay",
            "I'll live to see another day",
            "We can try to understand",
            "The New York Times' effect on man",
            "Whether you're a brother or whether you're a mother",
            "You're stayin' alive, stayin' alive",
            "Feel the city breakin' and everybody shakin'",
            "And we're stayin' alive, stayin' alive",
        ]
    },
    {
        "title": "Only the Good Die Young",
        "artist": "Billy Joel",
        "lyrics": [
            "Come out, Virginia, don't let me wait",
            "You Catholic girls start much too late",
            "Aw, but sooner or later, it comes down to fate",
            "I might as well be the one",
            "Well, they showed you a statue, told you to pray",
            "They built you a temple and locked you away",
            "Aw, but they never told you the price that you'd pay",
            "For things that you might have done",
            "Only the good die young",
            "That's what I said",
            "Only the good die young",
            "Only the good die young",
            "You might-a heard I run with a dangerous crowd",
            "We ain't too pretty, we ain't too proud",
            "We might be laughing a bit too loud",
            "Aw, but that never hurt no one",
            "So come on, Virginia, show me the sign",
            "Send up a signal, I'll throw you the line",
            "The stained-glass curtain you're hiding behind",
            "Never lets in the sun",
            "Darlin', only the good die young",
            "Ooh-whoa, whoa, whoa-oh",
            "I tell you only the good die young",
            "Only the good die young",
            "You've got a nice white dress and a party on your confirmation",
            "You've got a brand-new soul, mm, and a cross of gold",
            "But, Virginia, they didn't give you quite enough information",
            "You didn't count on me",
            "When you were countin' on your rosary, oh, whoa, whoa",
            "And they say there's a heaven for those who will wait",
            "Some say it's better, but I say it ain't",
            "I'd rather laugh with the sinners than cry with the saints",
        ]
    },
    {
        "title": "The Weight",
        "artist": "The Band",
        "lyrics": [
            "I pulled in to Nazareth",
            "Was feeling 'bout half past dead",
            "I just need someplace",
            "Where I can lay my head",
            "'Hey, mister, can you tell me",
            "Where a man might find a bed?'",
            "He just grinned and shook my hand",
            "'No' was all he said",
            "[Chorus]",
            "Take a load off, Fanny",
            "Take a load for free",
            "Take a load off, Fanny",
            "And (And, and)",
            "You put the load right on me (You put the load right on me)",
            "[Verse 2]",
            "I picked up my bag",
            "I went looking for a place to hide",
            "When I saw Carmen and the Devil",
            "Walking side-by-side",
            "I said, 'Hey Carmen",
            "Come on, let's go downtown'",
            "She said, 'I gotta go",
            "But my friend can stick around'",
            "Take a load off, Fanny",
            "Take a load for free",
            "Take a load off, Fanny",
            "And (And, and)",
            "You put the load right on me (You put the load right on me)",
        ]
    },
    {
        "title": "Goodbye Yellow Brick Road",
        "artist": "Elton John",
        "lyrics": [
            "When are you gonna come down",
            "When are you going to land",
            "I should have stayed on the farm",
            "I should have listened to my old man",
            "You know you can't hold me forever",
            "I didn't sign up with you",
            "I'm not a present for your friends to open",
            "This boy's too young to be singing the blues",
            "chorus:",
            "So goodbye yellow brick road",
            "Where the dogs of society howl",
            "You can't plant me in your penthouse",
            "I'm going back to my plough",
            "Back to the howling old owl in the woods",
            "Hunting the horny back toad",
            "Oh I've finally decided my future lies",
            "Beyond the yellow brick road",
            "What do you think you'll do then",
            "I bet that'll shoot down your plane",
            "It'll take you a couple of vodka and tonics",
            "To set you on your feet again",
            "Maybe you'll get a replacement",
            "There's plenty like me to be found",
            "Mongrels who ain't got a penny",
            "Sniffing for tidbits like you on the ground"
        ]
    },
    {
        "title": "Just Like Heaven",
        "artist": "The Cure",
        "lyrics": [
            "'Show me, show me, show me how you do that trick",
            "The one that makes me scream', she said",
            "'The one that makes me laugh', she said",
            "And threw her arms around my neck",
            "Show me how you do it",
            "And I promise you, I promise that",
            "I'll run away with you",
            "I'll run away with you",
            "Spinning on that dizzy edge",
            "I kissed her face and kissed her head",
            "And dreamed of all the different ways I had to make her glow",
            "'Why are you so far away', she said",
            "Why won't you ever know that I'm in love with you",
            "That I'm in love with you?",
            "You, soft and only",
            "You, lost and lonely",
            "You, strange as angels",
            "Dancing in the deepest oceans",
            "Twisting in the water",
            "You're just like a dream",
            "You're just like a dream",
            "Daylight licked me into shape",
            "I must have been asleep for days",
            "And moving lips to breathe her name",
            "I opened up my eyes",
            "And found myself alone, alone",
            "Alone above a raging sea",
            "That stole the only girl I loved",
            "And drowned her deep inside of me",
            "You, soft and lonely",
            "You, lost and lonely",
            "You, just like heaven"
        ]
    },
    {
        "title": "Free Bird",
        "artist": "Lynyrd Skynyrd",
        "lyrics": [
            "If I leave here tomorrow",
            "Would you still remember me?",
            "For I must be traveling on now",
            "'Cause there's too many places I've got to see",
            "But, if I stay here with you, girl",
            "Things just couldn't be the same",
            "'Cause, I'm as free as a bird now",
            "And this bird you cannot change, oh-oh-oh-oh-oh",
            "And the bird you cannot change",
            "And this bird you cannot change",
            "Lord knows I can't change",
            "Bye-bye, baby, it's been a sweet love, yeah, yeah",
            "Though this feeling I can't change",
            "But, please, don't take it so badly",
            "'Cause Lord knows I'm to blame",
            "But, if I stay here with you, girl",
            "Things just couldn't be the same",
            "'Cause, I'm as free as a bird now",
            "And this bird you'll never change, oh-oh-oh-oh-oh",
            "And the bird you cannot change",
            "And this bird you cannot change",
            "Lord knows I can't change",
            "Lord, help me, I can't cha-a-a-ange",
            "Lord, I can't change",
            "Won't you fly h-i-i-igh, free bird, yeah"
        ]
    },
    {
        "title": "Let Her Cry",
        "artist": "Hootie and the Blowfish",
        "lyrics": [
            "She sits alone by a lampost",
            "Trying to find a thought that's escaped her mind",
            "She says 'Dad's the one I love the most",
            "But Stipe's not far behind'",
            "She never lets me in",
            "Only tells me where she's been",
            "When she's had too much to drink",
            "I said that I don't care",
            "I just run my hands through her dark hair",
            "Then I pray to God, you gotta help me fly away",
            "And just let her cry, if the tears fall down like rain",
            "Let her sing, if it eases all her pain",
            "Let her go, let her walk right out on me",
            "And if the sun comes up tomorrow, let her be",
            "Let her be",
            "This morning I woke up alone",
            "Found a note standin' by the phone",
            "Saying 'Baby, maybe I'll be back someday'",
            "I wanted to look for you",
            "You walked in, I didn't know just what I should do",
            "So I sat back down and had a beer",
            "And felt sorry for myself, sayin'",
            "Let her cry, if the tears fall down like rain",
            "Let her sing, if it eases all her pain",
        ]
    },
    {
        "title": "Jesse's Girl",
        "artist": "Rick Springfield",
        "lyrics": [
            "Jessie is a friend",
            "Yeah, I know, he's been a good friend of mine",
            "But lately something's changed that ain't hard to define",
            "Jessie's got himself a girl and I want to make her mine",
            "And she's watching him with those eyes",
            "And she's loving him with that body, I just know it",
            "Yeah, and he's holding her in his arms late, late at night",
            "You know, I wish that I had",
            "Jessie's girl",
            "I wish that I had Jessie's girl",
            "Where can I find a woman like that?",
            "I'll play along with the charade",
            "There doesn't seem to be a reason to change",
            "You know, I feel so dirty when they start talking cute",
            "I wanna tell her that I love her, but the point is probably moot",
            "'Cause she's watching him with those eyes",
            "And she's loving him with that body, I just know it",
            "And he's holding her in his arms late, late at night",
            "You know, I wish that I had",
            "Jessie's girl",
            "I wish that I had Jessie's girl",
            "Where can I find a woman like that?",
            "Like Jessie's girl",
            "I wish that I had Jessie's girl",
            "Where can I find a woman-",
            "Where can I find a woman like that?",
            "And I'm looking in the mirror all the time",
            "Wonderin' what she don't see in me",
            "I've been funny, I've been cool with the lines",
            "Ain't that the way love's supposed to be?",
            "Tell me, where can I find a woman like that?",
            "You know, I wish that I had",
            "Jessie's girl",
            "I wish that I had Jessie's girl",
            "I want Jessie's girl",
            "Where can I find a woman like that?",
            "Like Jessie's girl",
            "I wish that I had Jessie's girl",
            "I want, I want Jessie's girl"
        ]
    },
    {
        "title": "Wake Me Up When September Ends",
        "artist": "Green Day",
        "lyrics": [
            "Summer has come and passed",
            "The innocent can never last",
            "Wake me up when September ends",
            "Like my father's come to pass",
            "Seven years has gone so fast",
            "Wake me up when September ends",
            "Here comes the rain again",
            "Falling from the stars",
            "Drenched in my pain again",
            "Becoming who we are",
            "As my memory rests",
            "But never forgets what I lost",
            "Wake me up when September ends",
            "Summer has come and passed",
            "The innocent can never last",
            "Wake me up when September ends",
            "Ring out the bells again",
            "Like we did when spring began",
            "Wake me up when September ends",
            "Here comes the rain again",
            "Falling from the stars",
            "Drenched in my pain again",
            "Becoming who we are",
            "As my memory rests",
            "But never forgets what I lost",
            "Wake me up when September ends",
            "Summer has come and passed",
            "The innocent can never last",
            "Wake me up when September ends",
            "Like my father's come to pass",
            "20 years has gone so fast",
            "Wake me up when September ends"
        ]
    },
    {
        "title": "Lay Down Sally",
        "artist": "Eric Clapton",
        "lyrics": [
            "There is nothing that is wrong",
            "In wanting you to stay here with me",
            "I know you've got somewhere to go",
            "But won't you make yourself at home and stay with me?",
            "And don't you ever leave",
            "Lay down, Sally, and rest here in my arms",
            "Don't you think you want someone to talk to?",
            "Lay down, Sally, no need to leave so soon",
            "I've been trying all night long just to talk to you",
            "Sun ain't nearly on the rise",
            "We still got the moon and stars above",
            "Underneath the velvet skies",
            "Love is all that matters, won't you stay with me?",
            "Don't you ever leave",
            "Lay down, Sally, and rest here in my arms",
            "Don't you think you want someone to talk to?",
            "Lay down, Sally, and no need to leave so soon",
            "I've been trying all night long just to talk to you",
            "I long to see the morning light",
            "Colour in your face so dreamily",
            "So don't you go and say goodbye",
            "You can lay your worries down and stay with me",
            "Don't you ever leave",
            "Lay down, Sally, and rest here in my arms",
            "Don't you think you want someone to talk to?",
            "Lay down, Sally, there's no need to leave so soon",
            "I've been trying all night long just to talk to you",
            "Lay down, Sally, and rest here in my arms",
            "Don't you think you want someone to talk to?",
            "Lay down, Sally, there's no need to leave so soon",
            "I've been trying all night long just to talk to you"
        ]
    },
    {
        "title": "Turn the Page",
        "artist": "Bob Seger and the Silver Bullet Band",
        "lyrics": [
            "This is from '72 also",
            "'Bout bein' on the road",
            "It's called 'Turn the Page', yeah",
            "One, two, three, and",
            "On a long and lonesome highway",
            "East of Omaha",
            "You can listen to the engine",
            "Moaning out its one-note song",
            "You can think about the woman",
            "Or the girl you knew the night before",
            "But your thoughts will soon be wanderin'",
            "The way they always do",
            "When you're riding sixteen hours",
            "And there's nothin' much to do",
            "And you don't feel much like riding",
            "You just wish the trip was through, mm",
            "Say, here I am",
            "On the road again",
            "There I am",
            "Up on the stage",
            "Here I go",
            "Playin' star again",
            "There I go",
            "Turn the page",
            "Well, you walk into a restaurant",
            "Strung out from the road",
            "And you feel the eyes upon you",
            "As you're shakin' off the cold",
            "You pretend it doesn't bother you",
            "But you just want to explode",
        ]
    },
    {
        "title": "Danny's Song",
        "artist": "Loggins and Messina",
        "lyrics": [
            "People smile and tell me I'm the lucky one",
            "And we've just begun",
            "Think I'm gonna have a son",
            "He will be like she and me, as free as a dove",
            "Conceived in love",
            "Sun is gonna shine above",
            "And even though we ain't got money",
            "I'm so in love with you, honey",
            "And everything will bring a chain of love, oh, oh, oh",
            "In the mornin', when I rise",
            "You bring a tear of joy to my eyes",
            "And tell me everything is gonna be alright",
            "Seems as though, a month ago, I was Beta-Chi",
            "Never got high",
            "Oh, was a sorry guy",
            "Now, I smile and face the girl that shares my name, yeah",
            "Now I'm through with the game",
            "This boy'll never be the same",
            "And even though we ain't got money",
            "I'm so in love with you, honey",
            "And everything will bring a chain of love, oh, oh, oh",
            "In the morning, when I rise",
            "You bring a tear of joy to my eyes",
            "And tell me everything is gonna be alright",
            "Pisces, Virgo rising is a very good sign",
            "Strong and kind",
            "And the little boy is mine",
            "Now I see a family where once was none",
            "Now we've just begun",
            "Yeah, we're gonna fly to the sun",
        ]
    },
    {
        "title": "Lemon Tree",
        "artist": "Fool's Garden",
        "lyrics": [
            "I'm sitting here in the boring room",
            "It's just another rainy Sunday afternoon",
            "I'm wasting my time, I got nothing to do",
            "I'm hanging around, I'm waiting for you",
            "But nothing ever happens and I wonder",
            "I'm driving around in my car",
            "I'm driving too fast, I'm driving too far",
            "I'd like to change my point of view",
            "I feel so lonely, I'm waiting for you",
            "But nothing ever happens and I wonder",
            "I wonder how",
            "I wonder why",
            "Yesterday you told me 'bout the blue blue sky",
            "And all that I can see is just a yellow lemon-tree",
            "I'm turning my head up and down",
            "I'm turning turning turning turning turning around",
            "And all that I can see is just another lemon-tree",
            "Sing",
            "Dap-dadada-dadpm-didap-da",
            "Dadada-dadpm-didap-da",
            "Dap-didili-da",
            "I'm sitting here, I miss the power",
            "I'd like to go out taking a shower",
            "But there's a heavy cloud inside my head",
            "I feel so tired, put myself into bed",
            "While nothing ever happens and I wonder",
            "Isolation is not good for me",
            "Isolation I don't want to sit on the lemon-tree",
            "I'm steppin' around in the desert of joy",
            "Baby anyhow I'll get another toy",
            "And everything will happen and you wonder"
        ]
    },
    {
        "title": "The Scientist",
        "artist": "Coldplay",
        "lyrics": [
            "Come up to meet you, tell ya I'm sorry",
            "You don't know how lovely you are",
            "I had to find you, tell ya I need you",
            "Tell you I set you apart",
            "Tell me your secrets and ask me your questions",
            "Oh, let's go back to the start",
            "Runnin' in circles, comin' up tails",
            "Heads on a science apart",
            "Nobody said it was easy",
            "It's such a shame for us to part",
            "Nobody said it was easy",
            "No one ever said it would be this hard",
            "Oh, take me back to the start",
            "I was just guessing at numbers and figures",
            "Pulling the puzzles apart",
            "Questions of science, science and progress",
            "Do not speak as loud as my heart",
            "But tell me you love me, come back and haunt me",
            "Oh, and I rush to the start",
            "Runnin' in circles, chasin' our tails",
            "Coming back as we are",
            "Nobody said it was easy",
            "Oh, it's such a shame for us to part",
            "Nobody said it was easy",
            "No one ever said it would be so hard",
            "I'm going back to the start"
        ]
    },
    {
        "title": "Accidentally In Love",
        "artist": "Counting Crows",
        "lyrics": [
            "So she said, what's the problem, baby?",
            "What's the problem? I don't know",
            "Well, maybe I'm in love (love)",
            "Think about it every time I think about it",
            "I can't stop thinking about it",
            "How much longer will it take to cure this?",
            "Just to cure it 'cause I can't ignore it if it's love (love)",
            "Makes me wanna turn around and face me",
            "But I don't know nothing 'bout love",
            "Come on, come on, turn a little faster",
            "Come on, come on, the world will follow after",
            "Come on, come on, because everybody's after love",
            "So I said I'm a snowball running",
            "Running down into the spring that's coming",
            "All this love melting under blue skies",
            "Belting out sunlight, shimmering love",
            "Well, baby, I surrender to the strawberry ice cream",
            "Never ever end of all this love",
            "Well, I didn't mean to do it",
            "But there's no escaping your love",
            "These lines of lightning mean we're never alone",
            "Never alone, no, no",
            "Come on, come on, move a little closer",
            "Come on, come on, I want to hear you whisper",
            "Come on, come on, settle down inside my love",
            "Come on, come on, jump a little higher",
            "Come on, come on, if you feel a little lighter",
            "Come on, come on, we were once upon a time in love",
            "We're accidentally in love",
            "Accidentally in love",
            "Come on, come on, spin a little tighter",
            "Come on, come on, and the world's a little brighter",
            "Come on, come on, just get yourself inside her love",
            "I'm in love"
        ]
    },
    {
        "title": "Crazy Little Thing Called Love",
        "artist": "Queen",
       "lyrics": [
        "This thing called love",
        "I just can't handle it",
        "This thing called love",
        "I must get 'round to it, I ain't ready",
        "Crazy little thing called love",
        "This thing, (this thing)",
        "Called love, (called love)",
        "It cries, (like a baby)",
        "In a cradle all night",
        "It swings, (wooh)",
        "It jives, (wooh)",
        "It shakes all over like a jelly fish",
        "I kinda like it",
        "Crazy little thing called love",
        "There goes my baby",
        "She knows how to rock and roll",
        "She drives me crazy",
        "She gives me hot and cold fever",
        "Then she leaves me in a cool, cool sweat",
        "I gotta be cool",
    ]
    },
    {
        "title": "Crocodile Rock",
        "artist": "Elton John",
        "lyrics": [
        "I remember when rock was young",
        "Me and Susie had so much fun",
        "Holding hands and skimming stones",
        "Had an old gold Chevy, and a place of my own",
        "But the biggest kick I ever got",
        "Was doing a thing called the Crocodile Rock",
        "While the other kids were rocking 'round the clock",
        "We were hopping and bopping to the Crocodile Rock, well",
        "Crocodile rocking is something shocking",
        "When your feet just can't keep still",
        "I never knew me a better time and I guess I never will",
        "Oh, lawdy mama those Friday nights",
        "When Suzie wore her dresses tight",
        "And the Crocodile rocking was out of sight",
        "Laa, la-la-la-la-laa",
        "La-la-la-la-laa",
        "La-la-la-la-laa",
        "But the years went by and the rock just died",
        "Suzie went and left me for some foreign guy",
    ]
    },
    {
        "title": "Fool in the Rain",
        "artist": "Led Zeppelin",
        "lyrics": [
        "Oh baby",
        "Well there's a light in your eye that keeps shinin'",
        "Like a star that can't wait for night",
        "I hate to think I been blinded baby",
        "Why can't I see you tonight?",
        "An' the warmth of your smile starts a burnin'",
        "An' the thrill of your touch give me fright",
        "And I'm shakin' so much, really yearnin'",
        "Why don't you show up and make it alright-yeah?",
        "It's alright-right",
        "And if you promised you'd love so completely",
        "An' you said you would always be true",
        "You swore that you never would leave me baby",
        "Whatever happened to you?",
        "An' you thought it was only in movies",
        "As you wish all your dreams would come true, hey",
        "It ain't the first time believe me baby",
        "I'm standin' here feelin' blue, blue-hah!",
    ]
    },
    {
        "title": "House of the Rising Sun",
        "artist": "The Animals",
        "lyrics": [
            "There is a house in New Orleans",
            "They call the Rising Sun",
            "And it's been the ruin of many a poor boy",
            "And God, I know I'm one",
            "My mother was a tailor",
            "She sewed my new blue jeans",
            "My father was a gamblin' man",
            "Down in New Orleans",
            "Now the only thing a gambler needs",
            "Is a suitcase and a trunk",
            "And the only time he'll be satisfied",
            "Is when he's on a trump",
            "Oh, mother, tell your children",
            "Not to do what I have done",
            "Spend your lives in sin and misery",
            "In the House of the Rising Sun",
            "Well, I got one foot on the platform",
            "The other foot on the train",
            "I'm goin' back to New Orleans",
            "To wear that ball and chain",
            "Well, there is a house in New Orleans",
            "They call the Rising Sun",
            "And it's been the ruin of many a poor boy",
            "And God, I know I'm one"
        ]
    },
    {
        "title": "Mona Lisa",
        "artist": "Nat King Cole",
        "lyrics": [
            "Mona Lisa, Mona Lisa, men have named you",
            "You're so like the lady with the mystic smile",
            "Is it only 'cause you're lonely they have blamed you?",
            "For that Mona Lisa strangeness in your smile?",
            "Do you smile to tempt a lover, Mona Lisa?",
            "Or is this your way to hide a broken heart?",
            "Many dreams have been brought to your doorstep",
            "They just lie there and they die there",
            "Are you warm, are you real, Mona Lisa?",
            "Or just a cold and lonely, lovely work of art?",
            "Do you smile to tempt a lover, Mona Lisa?",
            "Or is this your way to hide a broken heart?",
            "Many dreams have been brought to your doorstep",
            "They just lie there and they die there",
            "Are you warm, are you real, Mona Lisa?",
            "Or just a cold and lonely, lovely work of art?"
        ]
    },
    {
        "title": "Mona Lisas and Mad Hatters",
        "artist": "Elton John",
        "lyrics": [
            "Now I know",
            "'Spanish Harlem' are not just pretty words to say",
            "I thought I knew",
            "But now I know that rose trees never grow in New York City",
            "Until you've seen this trash can dream come true",
            "You stand at the edge while people run you through",
            "And I thank the Lord there's people out there like you",
            "I thank the Lord there's people out there like you",
            "While Mona Lisas and mad hatters",
            "Sons of bankers, sons of lawyers",
            "Turn around and say good morning to the night",
            "For unless they see the sky",
            "But they can't and that is why",
            "They know not if it's dark outside or light",
            "This Broadway's got",
            "It's got a lot of songs to sing",
            "If I knew the tunes I might join in",
            "I go my way alone",
            "Grow my own, my own seeds shall be sown in New York City",
            "Subway's no way for a good man to go down",
            "Rich man can ride and the hobo, he can drown",
            "And I thank the Lord for the people I have found",
            "I thank the Lord for the people I have found",
        ]
    },
    {
        "title": "Rhinestone Cowboy",
        "artist": "Glen Campbell",
        "lyrics": [
            "I've been walkin' these streets so long",
            "Singin' the same old song",
            "I know every crack in these dirty sidewalks of Broadway",
            "Where hustle's the name of the game",
            "And nice guys get washed away like the snow in the rain",
            "There's been a load of compromising",
            "On the road to my horizon",
            "But I'm gonna be where the lights are shinin' on me",
            "Like a rhinestone cowboy",
            "Riding out on a horse in a star-spangled rodeo",
            "Like a rhinestone cowboy",
            "Getting cards and letters from people I don't even know",
        ]
    },
    {
        "title": "Tiny Dancer",
        "artist": "Elton John",
        "lyrics": [
            "Blue-jean baby",
            "L.A. lady",
            "Seamstress for the band",
            "Pretty-eyed",
            "Pirate smile",
            "You'll marry a music man",
            "Ballerina",
            "You must've seen her",
            "Dancing in the sand",
            "And now she's in me",
            "Always with me",
            "Tiny dancer in my hand",
            "Jesus freaks",
            "Out in the street",
            "Handing tickets out for God",
            "Turning back",
            "She just laughs",
            "The boulevard is not that bad",
            "Piano man",
            "He makes his stand",
            "In the auditorium",
            "Looking on",
            "She sings the songs",
            "The words she knows",
        ]
    },
    {
        "title": "Why Don't We Get Drunk",
        "artist": "Jimmy Buffet",
        "lyrics": [
            "I really do appreciate",
            "The fact you're sitting here",
            "Your voice sounds so wonderful",
            "But your face don't look too clear",
            "So, barmaid, bring a pitcher",
            "Another round of brew",
            "Honey, why don't we get drunk and screw?",
            "Why don't we get drunk and screw?",
            "I just bought a waterbed",
            "It's filled up for me and you",
            "They say you are a snuff queen",
            "Honey, I don't think that's true",
            "So, why don't we get drunk and screw?",
            "Pick it Coral Reefers, here we go",
            "Why don't we get drunk and screw?",
            "I just bought a waterbed",
            "It's filled up for me and you",
            "They say you are a snuff queen",
            "Honey, I don't think that's true",
            "So, why don't we get drunk and screw?",
            "Yes, now baby, I say",
            "Why dont we get drunk and screw?"
        ]
    },
    {
        "title": "Wish You Were Here",
        "artist": "Pink Floyd",
        "lyrics": [
            "And disciplinary remains mercifully",
            "Yes and um, I'm with you, Derek, this star nonsense",
            "Yes, yes",
            "Now which is it?",
            "I am sure of it",
            "So, so you think you can tell",
            "Heaven from Hell, blue skies from pain?",
            "Can you tell a green field from a cold steel rail",
            "A smile from a veil? Do you think you can tell?",
            "Did they get you to trade your heroes for ghosts",
            "Hot ashes for trees, hot air for a cool breeze",
            "Cold comfort for change? Did you exchange",
            "A walk-on part in the war for a lead role in a cage?",
            "How I wish, how I wish you were here",
            "We're just two lost souls swimming in a fishbowl, year after year",
            "Running over the same old ground, what have we found?",
            "The same old fears, wish you were here"
        ]
    },
    {
        "title": "最长的电影",
        "artist": "周杰伦",
        "lyrics": [
            "我们的开始",
            "是很长的电影",
            "放映了三年",
            "我票都还留着",
            "冰上的芭蕾",
            "脑海中还在旋转",
            "望着你慢慢忘记你",
            "朦胧的时间",
            "我们溜了多远",
            "冰刀划的圈",
            "圈起了谁改变",
            "如果再重来",
            "会不会稍嫌狼狈",
            "爱是不是不开口才珍贵",
            "再给我两分钟",
            "让我把记忆结成冰",
        ]
    }
]