const vocabularyTerms = [
    {"Term":"Accidental","Definition":"Markings in the music that alter the pitch of a note"}, 
        {"Term":"Sharp","Definition":"Raises a natural pitch by one half step"}, 
        {"Term":"Flat","Definition":"Lowers a natural pitch by one half step"}, 
        {"Term":"Double Sharp","Definition":"Raises a natural pitch by two half steps"}, 
        {"Term":"Double Flat","Definition":"Lowers a natural pitch by two half steps"}, 
        {"Term":"Natural","Definition":"Returns a note to it's natural state, canceling any accidentals"}, 
        {"Term":"Enharmonic","Definition":"An alternate spelling of a note (i.e. C# and Db)"}, 
        {"Term":"Key","Definition":"The scale used in a piece of music"}, 
        {"Term":"Key Signature","Definition":"The set of sharps and flats which determine the key"}, 
        {"Term":"Solfege","Definition":"Do, Re, Mi, etc."}, 
        {"Term":"Scale","Definition":"The notes of a given key, ascending and descending"}, 
        {"Term":"Major Scale","Definition":"1, 2, 3, 4, 5, 6, 7, 8"}, 
        {"Term":"Natural Minor Scale","Definition":"1, 2,b3, 4, 5,b6,b7, 8"}, 
        {"Term":"Harmonic Minor Scale","Definition":"1, 2,b3, 4, 5,b6,nat.7, 8"}, 
        {"Term":"Melodic Minor Scale","Definition":"1, 2,b3, 4, 5,nat.6,nat.7, 8, b7,b6, 5, 4,b3, 2, 1 "}, 
        {"Term":"Relative Minor","Definition":"A minor scale that uses the same key signature as the major (C major, A minor)"}, 
        {"Term":"Parallel Minor","Definition":"A minor scale that shares the same tonic as the major (C major, C minor)"}, 
        {"Term":"Slur","Definition":"A curved line between two different pitches, indicating that they should be played legato"}, 
        {"Term":"Tie","Definition":"A curved line between two notes of the same pitch, adding their lengths together"}, 
        {"Term":"Rhythm","Definition":"The way of organizing notes by length"}, 
        {"Term":"Measure","Definition":"The space between two vertical bar lines"}, 
        {"Term":"Time Signature","Definition":"A marking that describes the number of beats in a measure and how they are subdivided"}, 
        {"Term":"Meter","Definition":"Another way to say Time Signature"}, 
        {"Term":"Simple Meter","Definition":"Beat is divisible by groups of two"}, 
        {"Term":"Compound Meter","Definition":"Beat is divisible by groups of three"}, 
        {"Term":"Complex Meter","Definition":"Some beats are divisible by two, some by three"}, 
        {"Term":"Duple Pulse","Definition":"Time signature with two main beats"}, 
        {"Term":"Triple Pulse","Definition":"Time signature with three main beats"}, 
        {"Term":"Quadruple Pulse","Definition":"Time signature with four main beats"}, 
        {"Term":"Downbeat","Definition":"The beginning or strongest part of the beat"}, 
        {"Term":"Upbeat","Definition":"The weaker subdivision(s) between the beats"}, 
        {"Term":"Syncopation","Definition":"The practice of accenting the upbeats of a phrase"}, 
        {"Term":"Tempo","Definition":"the speed of music"}, 
        {"Term":"BPM","Definition":"The number of beats per minute"}, 
        {"Term":"Ritardano","Definition":"To gradually decrease in speed"}, 
        {"Term":"Accelerando","Definition":"To gradually increase in speed"}, 
        {"Term":"A Tempo","Definition":"To return to the original tempo (after rit or accel)"}, 
        {"Term":"Rubato","Definition":"To be played with free tempo"}, 
        {"Term":"Largo or Lento","Definition":"Very slow, 40-60 BPM"}, 
        {"Term":"Adagio","Definition":"Slowly, with expression, 60-75 BPM"}, 
        {"Term":"Andante","Definition":"Walking tempo, 75-90 BPM"}, 
        {"Term":"Moderato","Definition":"At a moderate speed, 100-120 BPM"}, 
        {"Term":"Allegro","Definition":"Fast, 120-140 BPM"}, 
        {"Term":"Vivace","Definition":"Lively and fast, 150-175 BPM"}, 
        {"Term":"Presto","Definition":"Very fast, 140-200 BPM"}, 
        {"Term":"Dynamics","Definition":"Markings in music which determine how loudly or softly it is to be played"}, 
        {"Term":"Piano","Definition":"Quiet"}, 
        {"Term":"Forte","Definition":"Loud"}, 
        {"Term":"Mezzo Piano","Definition":"Moderately quiet"}, 
        {"Term":"Mezzo Forte","Definition":"Moderately loud"}, 
        {"Term":"Pianissimo","Definition":"Very quiet"}, 
        {"Term":"Fortissimo","Definition":"Very loud"}, 
        {"Term":"Crescendo","Definition":"Gradually growing in strength"}, 
        {"Term":"Decrescendo","Definition":"Gradually decreasing in strength"}, 
        {"Term":"Diminuendo","Definition":"A very gradual decrease in volume, usually over multiple measures"}, 
        {"Term":"Forte Piano","Definition":"A dynamic starting strong and immediately going to quiet"}, 
        {"Term":"Articulation","Definition":"The way a note is played (i.e. smoothly, sharply, lightly, etc.)"}, 
        {"Term":"Staccato","Definition":"To be played short and separated, lightly"}, 
        {"Term":"Legato","Definition":"To be played smoothly and flowingly; connected, no breaks"}, 
        {"Term":"Accent or Bell Tone","Definition":"A marking placed above or below a note head to indicate a loud start"}, 
        {"Term":"Marcato ","Definition":"To be played short and separated, but with emphasis"}, 
        {"Term":"Tenuto","Definition":"To be played at the full length of the full value of the note, stressed"}, 
        {"Term":"Sforzando","Definition":"To articulate a note with a strong, accented beginning and immediately drop to quiet"}, 
        {"Term":"Maestoso","Definition":"To be played majestically, by accenting every note"}, 
        {"Term":"Glissando","Definition":"To quickly slide from a low note to a high note, or vice versa"},
        {"Term": "Conjunct Motion", "Definition": "Smooth voice leading, usually by step"},
        {"Term": "Disjunct Motion", "Definition": "Voice leading characterized by large leaps"},
        {"Term": "Pentatonic Scale", "Definition": "A scale only using 5 notes, major or minor"},
        {"Term": "Chromatic Scale", "Definition": "A scale utilizing all 12 notes"},
        {"Term": "Whole Tone Scale", "Definition": "A scale comprised only of whole steps"},
        {"Term": "Octatonic Scale", "Definition": "A scale using 8 notes, diminished scales"},
        {"Term": "Improvisation", "Definition": "Come up with new melodies, solos, etc. on the spot"},
        {"Term": "Dissonance", "Definition": "A sound of clashing produced by conflicting notes"},
        {"Term": "Consonance", "Definition": "The opposite of dissonance, pleasant sounds"},
        {"Term": "Texture", "Definition": "The way in which musical content is presented"},
        {"Term": "Alberti Bass", "Definition": "The practice of arpeggiating the chords under the main melody"},
        {"Term": "Monophonic", "Definition": "A musical texture consisting of a single melody, if multiple voices, sung in unison"},
        {"Term": "Homophonic", "Definition": "A musical texture consisting of a main melody and harmony of lesser importance"},
        {"Term": "Polyphonic", "Definition": "A musical texture using multiple melodies, each with semi-equal importance"},
        {"Term": "Heterophonic", "Definition": "A musical texture of a melody that is doubled but with slight variations"},
        {"Term": "Solo", "Definition": "A performance by a single musician"},
        {"Term": "Duet", "Definition": "Two musicians performing together"},
        {"Term": "Trio", "Definition": "Three musicians performing together"},
        {"Term": "Quartet", "Definition": "Four musicians performing together"},
        {"Term": "Arpeggio", "Definition": "Playing a chord one note at a time instead of all at once"},
        {"Term": "Interval", "Definition": "The distance between two notes"},
        {"Term": "Perfect Unison", "Definition": "No distance between the pitches; the same note"},
        {"Term": "Minor 2", "Definition": "One half step between the pitches, 'Jaws'"},
        {"Term": "Major 2", "Definition": "Two half steps between the pitches, 'Do-re'"},
        {"Term": "Minor 3", "Definition": "Three half steps between the pitches, 'Funeral March'"},
        {"Term": "Major 3", "Definition": "Four half steps between the pitches, 'Mario'"},
        {"Term": "Perfect 4", "Definition": "Five half steps between the pitches, 'Here comes the bride,'"},
        {"Term": "Tritone", "Definition": "Six half steps between the pitches, 'The Simpsons'"},
        {"Term": "Perfect 5", "Definition": "Seven half steps between the pitches, 'Star Wars'"},
        {"Term": "Minor 6", "Definition": "Eight half steps between the pitches, 'Romance,' 'Bad Romance'"},
        {"Term": "Major 6", "Definition": "Nine half steps between the pitches, 'NBC,' 'Not At All'"},
        {"Term": "Minor 7", "Definition": "Ten half steps between the pitches, 'Winnie the Pooh'"},
        {"Term": "Major 7", "Definition": "Eleven half steps between the pitches, 'Pure Imagination'"},
        {"Term": "Perfect Octave", "Definition": "Twelve half steps between the pitches, space of 8 notes"},
        {"Term": "Soprano", "Definition": "The upper female voice"},
        {"Term": "Alto", "Definition": "The lower female voice"},
        {"Term": "Tenor", "Definition": "The upper male voice"},
        {"Term": "Bass", "Definition": "The lower male voice"},
        {"Term": "Diatonic", "Definition": "Chords or notes that fall within the scale"},
        {"Term": "Tonal Sequence", "Definition": "A sequence that stays in the same key, a diatonic sequence"},
        {"Term": "Ascend", "Definition": "To go up"},
        {"Term": "Descend", "Definition": "To go down"},
        {"Term": "Canon", "Definition": "A polyphonic texture created by playing or singing the same melody at different times"},
        {"Term": "Ostinato", "Definition": "A repeated musical phrase"},
        {"Term": "Countermelody", "Definition": "A secondary melody that accompanies the main one"},
        {"Term": "Sequence", "Definition": "A repetition of a musical phrase at a higher or lower pitch point"},
        {"Term": "Real Sequence", "Definition": "A sequence that keeps the exact intervalic relationships intact, usually outside of the key"},
        {"Term": "Theme", "Definition": "The main melodic subject of a piece"},
        {"Term": "Anacrusis", "Definition": "A pickup note that starts before the beginning of a phrase"},
        {"Term": "Transpose", "Definition": "To move all the notes of a song up or down"},
        {"Term": "Dictation", "Definition": "To write down a given melody or harmony"},
        {"Term": "Compound Interval", "Definition": "An interval that is larger than an octave, (reduce it by subtracting 7)"},
        {"Term": "Melismatic", "Definition": "To sing one syllable with many notes"},
        {"Term": "Syllabic", "Definition": "To sing one note per syllable"},
        {"Term": "Motive", "Definition": "A short melody but important to the song as a whole"},
        {"Term": "Hemiola", "Definition": "A temporary rhythmic juxtaposition of 3 and 2"},
        {"Term": "Cross Rhythm", "Definition": "A consistent overlapping of different rhythms or meters"},
        {"Term": "Rhythmic Diminution", "Definition": "Shortening the lengths of all notes in a phrase (doubling the speed)"},
        {"Term": "Rhythmic Augmentation", "Definition": "Lengthening the lengths of all notes in a phrase (slows the speed x2)"},
        {"Term": "Motive or Motif", "Definition": "A musical idea, a short piece of a theme"},
        {"Term": "Leitmotif", "Definition": "The practice of assigning themes and melodies to specific characters"},
        {"Term": "Melodic Inversion", "Definition": "To flip a melody vertically, to play it upside down"},
        {"Term": "Melodic Retrograde", "Definition": "To flip a melody horizontally, to play it backwards"},
        {"Term": "Fragmentation", "Definition": "Taking small pieces of a melody and using it to write others"},
        {"Term": "Imitation", "Definition": "The act of mimicking melodies in the same composition"},
        {"Term": "Walking Bass", "Definition": "A bassline that ascends and descends, scalularly"},
        {"Term":"Harmony","Definition":"The general concept that describes the way notes sound together"}, 
        {"Term":"Intonation","Definition":"The act of being in tune"}, 
        {"Term":"Chord","Definition":"Multiple notes sounded simultaneously, triads, etc."}, 
        {"Term":"Triad","Definition":"a three note chord: 1,3,5"}, 
        {"Term":"Major Triad","Definition":"1 M3 P5,   (1    3    5)"}, 
        {"Term":"Minor Triad","Definition":"1 m3 P5,   (1 b3    5)"}, 
        {"Term":"Diminished Triad","Definition":"1 m3 d5,   (1 b3 b5)"}, 
        {"Term":"Augmented Triad","Definition":"1 M3 A5,  (1    3   #5)"}, 
        {"Term":"Tonic","Definition":"I, do-mi-sol"}, 
        {"Term":"Supertonic","Definition":"ii, re-fa-la"}, 
        {"Term":"Mediant","Definition":"iii, mi-sol-xi"}, 
        {"Term":"Subdominant","Definition":"IV, fa-la-do"}, 
        {"Term":"Dominant","Definition":"V, sol-xi-re"}, 
        {"Term":"Submediant","Definition":"vi, la-do-mi"}, 
        {"Term":"Leading Tone","Definition":"viiº, xi-re-fa"}, 
        {"Term":"Root","Definition":"The tonic (1) of a given chord"}, 
        {"Term":"Root Position","Definition":"The root of the chord is on the bottom"}, 
        {"Term":"Inversion","Definition":"A voicing of a chord where the root is not on bottom"}, 
        {"Term":"First Inversion","Definition":"A chord with the 3rd on the bottom, abbr. 6"}, 
        {"Term":"Second Inversion","Definition":"A chord with the 5th on the bottom, abbr. 64"}, 
        {"Term":"Figured Bass","Definition":"The practice of only writing the bass note and inversion symbols "}, 
        {"Term":"Basso Continuo","Definition":"During the Baroque era, the group of musicians providing harmony"}, 
        {"Term":"Arpeggiating 64","Definition":"A 64 in which the harmony stays the same, but the bass changes"}, 
        {"Term":"Cadential 64","Definition":"I64, V, I"}, 
        {"Term":"Passing 64","Definition":"A 64 that is passed through to another harmony"}, 
        {"Term":"Pedal 64","Definition":"A 64 in which the bass stays the same, but the harmony changes"}, 
        {"Term":"Open Voicing","Definition":"A voicing in which there are unused notes"}, 
        {"Term":"Close Voicing","Definition":"A voicing in which neighboring voices use the next available chord tone"}, 
        {"Term":"Keyboard Voicing","Definition":"Only one note is used in the bass, and the treble clef uses close voicing"}, 
        {"Term":"Seventh Chord","Definition":"a four note chord: 1,3,5,7"}, 
        {"Term":"Major 7 chord","Definition":"1 M3 P5 M7"}, 
        {"Term":"Dominant 7 chord","Definition":"1 M3 P5 m7"}, 
        {"Term":"Minor 7 chord","Definition":"1 m3 P5 m7"}, 
        {"Term":"Half-Diminished 7 chord","Definition":"1 m3 d5 m7"}, 
        {"Term":"Diminished 7 chord","Definition":"1 m3 d5 d7"}, 
        {"Term":"Function","Definition":"The specific role (job) that a chord plays "}, 
        {"Term":"Cadence","Definition":"A resting point at the end of a musical phrase"},
        {"Term": "Part Writing", "Definition": "Realizing a given harmony in four voices"},
        {"Term": "Outer Voices", "Definition": "Bass and Soprano voices"},
        {"Term": "Inner Voices", "Definition": "Alto and Tenor voices"},
        {"Term": "Motion", "Definition": "The movement of notes in relation to each other"},
        {"Term": "Similar Motion", "Definition": "The two voices move in the same direction, but not by the same intervals"},
        {"Term": "Contrary Motion", "Definition": "The two voices move in the opposite direction of one another"},
        {"Term": "Parallel Motion", "Definition": "The two voices move in the same direction by the same interval"},
        {"Term": "Oblique Motion", "Definition": "One voice remains the same and the other moves, in either direction"},
        {"Term": "Static Motion", "Definition": "Both voices repeat their same note, no movement"},
        {"Term": "Active or Tendency Tones", "Definition": "Notes that tend to pull in a specific direction"},
        {"Term": "Chord Tone", "Definition": "A note that belongs to the current harmony"},
        {"Term": "Non-Chord Tone", "Definition": "A tone in a particular harmony that does not belong to that chord"},
        {"Term": "Passing Tone", "Definition": "An NCT that bridges two notes of differing harmony"},
        {"Term": "Neighbor Tone", "Definition": "An NCT that goes immediately next to a CT and returns"},
        {"Term": "Escape Tone", "Definition": "An NCT that steps in the opposite direction of its destination note, and then skips to it"},
        {"Term": "Appoggiatura", "Definition": "An NCT that skips above its intended destination note, and then steps down to it"},
        {"Term": "Anticipation", "Definition": "An NCT that belongs to the second harmony rather than that of the first"},
        {"Term": "Suspension", "Definition": "An NCT that holds over from a previous harmony and then resolves down"},
        {"Term": "Retardation", "Definition": "An NCT that holds over from a previous harmony and then resolves up"},
        {"Term": "Pedal Point or Tone", "Definition": "An NCT that holds underneath or above several different harmonies"},
        {"Term": "Syncope", "Definition": "A systematic rhythmic anticipation of the following harmony"},
        {"Term": "Changing Tones", "Definition": "Also called 'neighbor group' or 'cambiata' two notes on either side of the following CT"},
        {"Term": "Accented (NCT)", "Definition": "A non chord tone that falls on the strong beat of a measure"},
        {"Term": "Authentic Cadence", "Definition": "A cadence from the dominant (V) to tonic (I or i)"},
        {"Term": "Perfect Authentic Cadence", "Definition": "An authentic cadence with both chords in root position, soprano ends on tonic"},
        {"Term": "Imperfect Authentic Cadence", "Definition": "An Authentic cadence with inversions or non-tonic in the soprano voice"},
        {"Term": "Plagal Cadence", "Definition": "A cadence from the subdominant (IV) to tonic (I)"},
        {"Term": "Deceptive Cadence", "Definition": "A cadence from V to vi (major) or V to VI (minor)"},
        {"Term": "Half Cadence", "Definition": "A cadence that ends on the dominant"},
        {"Term": "Phrygian Half Cadence", "Definition": "A half cadence that descends from a iv6 to a V"},
        {"Term": "Minor Plagal Cadence", "Definition": "Cadence from a minor iv to major I"},
        {"Term": "Picardy Third", "Definition": "A resolution at the end of a minor song that finishes on a major I"},
        {"Term": "Predominant", "Definition": "A harmony that precedes the V chord"},
        {"Term": "Function", "Definition": "The specific role (job) that a chord plays"},
        {"Term": "Cadence", "Definition": "A resting point at the end of a musical phrase"},
        {"Term": "Contrasting Period", "Definition": "A period in which both phrases start with different material"},
        {"Term": "Predominant", "Definition": "A category of chord whose function is to precede a V chord"},
        {"Term": "Period", "Definition": "A set of two phrases, one ending in a HC and the second ending in a AC"},
        {"Term": "Parallel 5ths or 8ves", "Definition": "When two voices, an octave or 5th apart move in the same direction by the same interval"},
        {"Term": "Chromatic", "Definition": "Moving by half steps (leaving the key)"},
        {"Term": "Tonicize", "Definition": "To temporarily use a new key center in a musical passage"},
        {"Term": "Range", "Definition": "The total span of notes a given instrument or voice type can play or sing"},
        {"Term": "Parallel Modulation", "Definition": "To keep the same tonic but change from major to minor, or vice versa"},
        {"Term": "Key Change", "Definition": "When the root key of a particular piece shifts to another center"},
        {"Term": "Crossed Voices", "Definition": "When any lower voice has a note higher than the upper voice, or vice versa"},
        {"Term": "Parallel Period", "Definition": "A period in which both phrases start with the same material"},
        {"Term": "Secondary Dominant", "Definition": "A five (V) of some diatonic chord, leads to new keys"},
        {"Term": "Overlapping Voices", "Definition": "When any lower voice has a note higher than the previously sung note of the upper voice"},
        {"Term": "Modulate", "Definition": "To slowly change from one key to another, the process of changing keys"},
        {"Term": "Function", "Definition": "How a chord works in the context of others, how it resolves, etc."},
        {"Term": "Secondary Leading Tone", "Definition": "A seven (vii) of some diatonic chord, leads to new keys"},
        {"Term": "Tendency Tones", "Definition": "Voices that should resolve in certain ways (i.e. in a V7 chord, the 7th down, 3rd up)"},
        {"Term": "Voice Leading", "Definition": "The concept of how individual notes in a part move to the next note (ideally smoothly)"},
        {"Term": "Direct or Hidden 5ths", "Definition": "When the soprano skips up or down and the bass moves in similar motion to a 5th or 8ve"},
        {"Term": "Spacing", "Definition": "The intervalic distance between any two consecutive voice parts"},
        {"Term": "Direct Modulation", "Definition": "To move immediately from one key into another with no transition"},
        {"Term": "Resolution", "Definition": "The specific direction that active tones should move, how they resolve"},
        {"Term":"Modes","Definition":"Scales that start from degrees other than Do (Re to Re, Mi to Mi, etc.)"}, 
        {"Term":"Ionian","Definition":"Major Scale"}, 
        {"Term":"Dorian","Definition":"Minor Scale with Natural 6"}, 
        {"Term":"Phrygian","Definition":"Minor Scale with Flat 2"}, 
        {"Term":"Lydian","Definition":"Major Scale with Sharp 4"}, 
        {"Term":"Mixolydian","Definition":"Major Scale with Flat 7"}, 
        {"Term":"Aeolian","Definition":"Natural Minor Scale"}, 
        {"Term":"Locrian","Definition":"Minor Scale with Flat 2 & 5"}, 
        {"Term":"Augmented 6 chord","Definition":"A chord that precedes the V chord by half steps from the inside"}, 
        {"Term":"Italian Aug 6","Definition":"An Augmented 6 chord with degrees 1,3, and 7"}, 
        {"Term":"German Aug 6","Definition":"An Augmented 6 chord with degrees 1,3,5, and 7"}, 
        {"Term":"French Aug 6","Definition":"An Augmented 6 chord with degrees 1,3,#4, and 7"}, 
        {"Term":"Neapolitan 6 Chord","Definition":"A major chord built off of the flat 2, usually in first inversion"}, 
        {"Term":"Harmonic Rhythm","Definition":"How fast chords change in a piece"}, 
        {"Term":"Ornaments","Definition":"Notes added to give more interest to a melody (to make it fancier)"}, 
        {"Term":"Contour","Definition":"The shape of a given melody or phrase"},
    ];